development:
  adapter: sqlite3
  database: db/development.sqlite3
  host: localhost

production:  
  adapter: postgresql
  encoding: unicode
  database: db/production
  pool: 2
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>